@host = http://localhost:4444
###
GET {{host}}/videos/

###
GET {{host}}/videos/600b61ccc53a02c75894c35a

###
POST {{host}}/videos/
Content-Type: application/json

{
	"title":"Instant Crush",
	"url": "https://www.youtube.com/watch?v=a5uQMwRMHcs",
	"description": "A daft punk song:("
}
###
DELETE {{host}}/videos/600b61ccc53a02c75894c35a