@host = http://localhost:4444
###
GET {{host}}/videos/

###
POST {{host}}/videos/
Content-Type: application/json

{
	"title":"Rosseau piano collection",
	"url": "https://www.youtube.com/watch?v=cGYyOY4XaFs",
	"description": "A bunch of classical piano songs"
}
###
DELETE {{host}}/videos/